<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="eb07b1f8cf311f0aaca16d0d2272db5_1.jpeg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="eb07b1f8cf311f0aaca16d0d2272db5_1.jpeg" />
  </ItemGroup>

</Project>
